using System.Security.Claims;
using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
using MindCare.Data; using MindCare.Models; using MindCare.ViewModels;
namespace MindCare.Controllers;
[Authorize(Roles=RoleNames.Admin)] public class AdminResourcesController(ApplicationDbContext context):Controller
{
 public async Task<IActionResult> Index(){return View(await context.Resources.Include(r=>r.ResourceCategory).Include(r=>r.CreatedByUser).OrderByDescending(r=>r.UpdatedAt).ToListAsync());}
 public async Task<IActionResult> Pending()=>View(await context.Resources.Include(r=>r.ResourceCategory).Include(r=>r.CreatedByUser).Where(r=>r.Status==ResourceStatus.PendingReview).OrderBy(r=>r.SubmittedAt).ToListAsync());
 public async Task<IActionResult> Create()=>View(await Form());
 [HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> Create(ResourceEditViewModel m,string command){if(!ModelState.IsValid){m.Categories=await Categories();return View(m);}var now=DateTime.UtcNow;var r=new Resource{CreatedAt=now,UpdatedAt=now,CreatedByUserId=User.FindFirstValue(ClaimTypes.NameIdentifier),CreatedByRole=RoleNames.Admin};Map(r,m);Set(r,command);context.Resources.Add(r);await context.SaveChangesAsync();return RedirectToAction(nameof(Index));}
 public async Task<IActionResult> Edit(int id){var r=await context.Resources.FindAsync(id);return r is null?NotFound():View(await Form(r));}
 [HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> Edit(int id,ResourceEditViewModel m,string command){var r=await context.Resources.FindAsync(id);if(r is null)return NotFound();if(!ModelState.IsValid){m.Categories=await Categories();return View(m);}Map(r,m);r.UpdatedAt=DateTime.UtcNow;Set(r,command);await context.SaveChangesAsync();return RedirectToAction(nameof(Index));}
 public async Task<IActionResult> Review(int id){var r=await context.Resources.Include(r=>r.ResourceCategory).Include(r=>r.CreatedByUser).SingleOrDefaultAsync(r=>r.Id==id&&r.Status==ResourceStatus.PendingReview);return r is null?NotFound():View(r);}
 [HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> Approve(int id){var r=await context.Resources.FindAsync(id);if(r is null)return NotFound();if(r.Status!=ResourceStatus.PendingReview)return BadRequest();Publish(r);Log(r,"Approved",null);await context.SaveChangesAsync();TempData["SuccessMessage"]="Resource approved and published.";return RedirectToAction(nameof(Pending));}
 [HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> Reject(ResourceReviewViewModel m){var r=await context.Resources.FindAsync(m.Id);if(r is null)return NotFound();if(r.Status!=ResourceStatus.PendingReview||!ModelState.IsValid)return BadRequest();r.Status=ResourceStatus.Rejected;r.ReviewedAt=r.UpdatedAt=DateTime.UtcNow;r.ReviewedByAdminId=User.FindFirstValue(ClaimTypes.NameIdentifier);r.ReviewNote=m.ReviewNote.Trim();Log(r,"Rejected",r.ReviewNote);await context.SaveChangesAsync();TempData["SuccessMessage"]="Resource returned to the counsellor for revision.";return RedirectToAction(nameof(Pending));}
 [HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> Archive(int id){var r=await context.Resources.FindAsync(id);if(r is null)return NotFound();if(r.Status is not (ResourceStatus.Published or ResourceStatus.Draft or ResourceStatus.Rejected))return BadRequest();r.Status=ResourceStatus.Archived;r.ArchivedAt=r.UpdatedAt=DateTime.UtcNow;r.IsFeatured=false;Log(r,"Archived",null);await context.SaveChangesAsync();return RedirectToAction(nameof(Index));}
 [HttpPost,ValidateAntiForgeryToken] public async Task<IActionResult> Restore(int id){var r=await context.Resources.FindAsync(id);if(r is null)return NotFound();if(r.Status!=ResourceStatus.Archived)return BadRequest();r.Status=ResourceStatus.Draft;r.UpdatedAt=DateTime.UtcNow;r.ArchivedAt=null;Log(r,"Restored",null);await context.SaveChangesAsync();return RedirectToAction(nameof(Index));}
 private Task<List<ResourceCategory>> Categories()=>context.ResourceCategories.Where(c=>c.IsActive).OrderBy(c=>c.Name).ToListAsync();private async Task<ResourceEditViewModel> Form(Resource? r=null)=>new(){Id=r?.Id??0,Title=r?.Title??"",Description=r?.Description??"",CategoryId=r?.CategoryId,Content=r?.Content??"",Url=r?.Url,IsFeatured=r?.IsFeatured??false,Categories=await Categories()};private static void Map(Resource r,ResourceEditViewModel m){r.Title=m.Title.Trim();r.Description=m.Description.Trim();r.Content=m.Content.Trim();r.CategoryId=m.CategoryId;r.Url=m.Url?.Trim();r.IsFeatured=m.IsFeatured;}private void Set(Resource r,string c){if(c=="publish")Publish(r);else r.Status=ResourceStatus.Draft;}private void Publish(Resource r){var now=DateTime.UtcNow;r.Status=ResourceStatus.Published;r.PublishedAt??=now;r.ReviewedAt=now;r.ReviewedByAdminId=User.FindFirstValue(ClaimTypes.NameIdentifier);r.ReviewNote=null;r.UpdatedAt=now;}private void Log(Resource r,string a,string? n)=>context.ResourceReviewLogs.Add(new(){ResourceId=r.Id,AdminUserId=User.FindFirstValue(ClaimTypes.NameIdentifier)!,Action=a,Note=n,CreatedAt=DateTime.UtcNow});
}
